codecov:
  token: "" # Será configurado via secrets do GitHub

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 100%
        threshold: 1%
        if_not_found: success
        informational: false
    patch:
      default:
        target: 100%
        threshold: 1%
        if_not_found: success
        informational: false

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true

ignore:
  - "examples/**/*"
  - "**/*.g.dart"
  - "**/*.mocks.dart"
  - "**/test/**"

flags:
  unittests:
    paths:
      - lib/
    carryforward: false
