name: engine_security
description: Advanced security detection system for Flutter applications focused on Android and iOS. Detects Frida, Root/Jailbreak, Emulator, and Debugger threats with high precision.
version: 1.2.1
homepage: https://stmr.tech
repository: https://github.com/moreirawebmaster/engine-security
issue_tracker: https://github.com/moreirawebmaster/engine-security/issues
documentation: https://github.com/moreirawebmaster/engine-security#readme

funding:
  - https://github.com/sponsors/moreirawebmaster

topics:
  - security
  - detection
  - frida
  - mobile
  - android

platforms:
  android:
  ios:

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: 9.1.2
  crypto: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.15
  flutter_lints: ^6.0.0
  coverage: ^1.14.1
