name: engine_security
description: Plugin Flutter para funcionalidades de segurança, detecção de frida, emulador, root/jailbreak do Engine Framework
version: 1.0.0
homepage: https://github.com/moreirawebmaster/engine
repository: https://github.com/moreirawebmaster/engine

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: any
  package_info_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
