name: security_demo
description: "Demo app para testar funcionalidades de segurança do Engine Security"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  engine_security:
    path: ../../

  flutter_riverpod: ^2.5.1
  go_router: ^15.2.4
  permission_handler: ^12.0.0+1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
